filter:
    excluded_paths:
        - wp-content/mu-plugins/site-setup/includes/auto-install-plugins.php
        - wp-content/mu-plugins/site-setup/includes/class-tgm-plugin-activation.php
        - wp-content/mu-plugins/assets/metabox/*
        - wp-content/mu-plugins/assets/tests/*